# Generated by Django 4.1.4 on 2023-01-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bought_user_alter_commentary_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('shipping_price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customizable',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.AddField(
            model_name='bought',
            name='accumulated',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bought',
            name='customizable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bought',
            name='phone',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='bought',
            name='quantity_of_products',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bought',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipt'),
        ),
        migrations.AddField(
            model_name='bought',
            name='references',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customizable',
            name='amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='productbougth',
            name='accumulated',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productbougth',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
