# Generated by Django 4.1.4 on 2023-01-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_province_remove_customizable_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bought',
            name='receipt',
            field=models.ImageField(default=None, upload_to='receipt'),
        ),
    ]
