# Generated by Django 4.1.4 on 2023-01-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_category_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='brand',
        ),
    ]
