# Generated by Django 4.1.4 on 2023-01-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_brand_alter_product_stock_filamet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filamet',
            new_name='Filament',
        ),
    ]
