# Generated by Django 4.1.4 on 2023-01-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_filament_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='filament',
            name='name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
